server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8020

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:./db/sampledb
  user:
  password:
  validationQuery: select 1
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.current_session_context_class: thread
    # remove this for connecting to an existing database !!!!!
    hibernate.hbm2ddl.auto: create

ldapConfiguration:
  uri: ldap://ldap.example.com:389/dc=yourcompany,dc=com
  userFilter: dc=yourcompany,dc=com
  user: ldapadminacct
  pwd: supersecretadmpwd
  userNameAttribute: uid
  connectTimeout: 500ms
  readTimeout: 500ms
  negotiateTls: none
  # Roles in this application are defined
  # by 'ou' in LDAP
  allowedRoles:
    - admin
    - staff

logging:
  appenders:
    - type: file
      currentLogFilename: ./logs/wizbangapi.log
      archivedLogFilenamePattern: ./logs/example-%d.log.gz
      archivedFileCount: 10
      timeZone: UTC
      logFormat: "%level %mdc{user:-NOUSER} %d [%thread] %logger{32} - %msg%n"
    - type: console
      timeZone: UTC
      logFormat: "%level %mdc{user:-NOUSER} %d [%thread] %logger{32} - %msg%n"
